<?php

/**
 * PluginTimelineEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTimelineEventTable extends Doctrine_Table
{
  public function getTimeline()
  {
    $all = $this->createQuery('te')->execute();

  }
}