TimelineEvent:
  actAs:
    Timestampable: ~ 
  columns:
    event_type:
      type: string(255)
    subject_type:
      type: string(255)
    subject_id:
      type: integer
    actor_type:
      type: string(255)
    actor_id:
      type: integer
    secondary_subject_type:
      type: string(255)
    secondary_subject_id:
      type: integer    
   
   
   
   